CostosDeDespacho/CostosDeDespacho/Controllers/PanelJumpSController.cs
using CostosDeDespacho.App_Code.BL;
using CostosDeDespacho.App_Code.CONSTANTES;
using CostosDeDespacho.App_Code.DTO;
using CostosDeDespacho.App_Code.DTO.Jumpseller;
using CostosDeDespacho.App_Code.Utils;
using CostosDeDespacho.Models;
using iTextSharp.text.pdf;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Net;
using System.Web.Mvc;


namespace CostosDeDespacho.Controllers
{
    public class PanelJumpSController : Controller
    {
        //private static readonly HttpClient client = new HttpClient();
        private const string keySessionCredencialesAPI = "objJumpsellerApi";
        private const string keySessionJumpsellerStore = "objJumpsellerStore";

        private JUMPSELLER_STORES objJumpsellerStore;

        [HttpGet]
        public ActionResult setTokenShipex(string store_id)
        {
            try
            {
                Log.Debug("setTokenShipex store_id" + store_id);
                ViewBag.idJumpsellerStore = store_id;
                db_shipexEntities context = new db_shipexEntities();
                int storeId = Convert.ToInt32(store_id);
                JUMPSELLER_STORES objJumpsellerStore = context.JUMPSELLER_STORES.Where(x => x.id_tienda_jumpseller == storeId && x.activo == true).FirstOrDefault();
                if (objJumpsellerStore.Api_Key != null)
                {
                    ViewBag.api_token = objJumpsellerStore.Api_Key.token.ToString();
                }
            }
            catch (Exception e)
            {
                Log.Fatal("Error setTokenShipex GET " + e.ToString());
            }
            return View();
        }

        [HttpPost]
        public ActionResult setTokenShipex(string idJumpsellerStore, string token)
        {
            ViewBag.idJumpsellerStore = idJumpsellerStore;
            int idStore = Convert.ToInt32(idJumpsellerStore);
            JumpsellerAPI objJumpsellerApi = this.getJumpsellerAPIObj(idStore);
            db_shipexEntities context = new db_shipexEntities();
            int storeId = Convert.ToInt32(idJumpsellerStore);
            JUMPSELLER_STORES objJumpsellerStore = context.JUMPSELLER_STORES.Where(x => x.id_tienda_jumpseller == storeId && x.activo == true).FirstOrDefault();
            Api_Key objApiKey = context.Api_Key.Where(x => x.token.Equals(token)).FirstOrDefault();
            if (objApiKey != null)
            {
                JumpsellerOperacionesAPI objOperacionesAPIJumpseller = new JumpsellerOperacionesAPI(objJumpsellerApi.token_type, objJumpsellerApi.access_token);
                ShippingMethodWrapper objShippingMethod = objOperacionesAPIJumpseller.createShippingMethod(token);
                if (objShippingMethod != null && objShippingMethod.shipping_method != null)
                {
                    //posterior a crear el shipping en la tienda debo asociar la tienda con el token
                    db_shipexEntities contextSave = new db_shipexEntities();
                    JUMPSELLER_STORES objSearchStore = contextSave.JUMPSELLER_STORES.Where(x => x.id == objJumpsellerStore.id).FirstOrDefault();
                    objSearchStore.fecha_ingreso_token = DateTime.Now;
                    objSearchStore.shipex_token_ingresado = true;
                    objSearchStore.activo = true;
                    objSearchStore.id_shipping_method = objShippingMethod.shipping_method.id;
                    objSearchStore.API_KEY_id_token = objApiKey.id;
                    contextSave.Entry(objSearchStore).State = EntityState.Modified;

                    //Registro de webhook
                    string urlProcesaOrdenWebhook = ConfigurationManager.AppSettings["app.jumpseller.url.processOrderWebhook"];
                    string eventName = ConfigurationManager.AppSettings["api.jumpseller.hook.order.paid"];
                    bool resCreacion = objOperacionesAPIJumpseller.createWebhook(eventName, urlProcesaOrdenWebhook);
                    //Fin registro de webhook

                    contextSave.SaveChanges();
                    this.setValorSession(keySessionJumpsellerStore, objSearchStore);
                    return RedirectToAction("panelOrdenes", new { store_id = objSearchStore.id_tienda_jumpseller });
                }
            }
            else
            {
                return View();
            }
            return View();
        }

        [HttpPost]
        public ActionResult panelOrdenes(string idOrden, string fecDesde, string fecHasta, string idJumpsellerStore)
        {

            //Caso sin filtro, solo se redirecicona al controlador por get
            ViewBag.idJumpsellerStore = idJumpsellerStore;
            if (fecDesde.Equals("") && fecHasta.Equals("") && idOrden.Trim().Equals(""))
            {
                Log.Debug("redireccionando ..." + idJumpsellerStore);
                return RedirectToAction("panelOrdenes", new { store_id = idJumpsellerStore });
            }

            List<PanelOrderJumpsellerViewModel> lOrderJumsellerVM = new List<PanelOrderJumpsellerViewModel>();
            try
            {
                int idStore = Convert.ToInt32(idJumpsellerStore);
                db_shipexEntities objConexion = new db_shipexEntities();
                JUMPSELLER_STORES objJumpsellerStore = objConexion.JUMPSELLER_STORES.Where(x => x.id_tienda_jumpseller == idStore && x.activo == true).FirstOrDefault();
                int nOrden;
                bool resCambioOrden = false;
                JUMPSELLER_ORDERS objOrdenBusquedaId;

                bool conFechas = fecDesde != null && !fecDesde.Trim().Equals("") && fecHasta != null && !fecHasta.Trim().Equals("") ? true : false;
                bool conOrden = idOrden != null && !idOrden.Trim().Equals("") ? true : false;
                //Solo busco por orden
                if (conOrden == true && conFechas == false)
                {
                    resCambioOrden = Int32.TryParse(idOrden.Trim(), out nOrden);
                    objOrdenBusquedaId = objConexion.JUMPSELLER_ORDERS.Where(x => x.order_id == nOrden && x.jumpseller_store_id == objJumpsellerStore.id).FirstOrDefault();
                    PanelOrderJumpsellerViewModel objOrderJumpsellerVM = new PanelOrderJumpsellerViewModel();
                    objOrderJumpsellerVM.comuna = objOrdenBusquedaId.comuna;
                    objOrderJumpsellerVM.direccionEnvio = objOrdenBusquedaId.direccion_envio;
                    objOrderJumpsellerVM.email = objOrdenBusquedaId.email;
                    objOrderJumpsellerVM.estadoEnvioShipex = objOrdenBusquedaId.SHIPEX_API_ESTADOS.estado;
                    objOrderJumpsellerVM.estadoOrdenJumpseller = objOrdenBusquedaId.status;
                    objOrderJumpsellerVM.id = objOrdenBusquedaId.id;
                    objOrderJumpsellerVM.id_orden_jumpseller = objOrdenBusquedaId.order_id.ToString();
                    objOrderJumpsellerVM.nombreReceptor = objOrdenBusquedaId.nombre_receptor;
                    objOrderJumpsellerVM.telefono = objOrdenBusquedaId.telefono;
                    lOrderJumsellerVM.Add(objOrderJumpsellerVM);
                    ViewBag.idOrden = idOrden;
                }

                //Busco solo por fechas
                if (conOrden == false && conFechas == true)
                {
                    String procAlmacenado = "exec FILTRAR_ORDENES_JUMPSELLER '@fechaInicio', '@fechaFin', '@idStore'";
                    procAlmacenado = procAlmacenado.Replace("@fechaInicio", fecDesde);
                    procAlmacenado = procAlmacenado.Replace("@fechaFin", fecHasta);
                    procAlmacenado = procAlmacenado.Replace("@idStore", objJumpsellerStore.id.ToString());
                    PanelOrderJumpsellerViewModel objOrderJumpsellerVM = objConexion.Database.SqlQuery<PanelOrderJumpsellerViewModel>(procAlmacenado).FirstOrDefault();
                    lOrderJumsellerVM.Add(objOrderJumpsellerVM);
                }
            }
            catch (Exception ex)
            {
                Log.Fatal("Error panelOrdenes post " + ex.ToString());
            }

            return View(lOrderJumsellerVM);
        }

        [HttpGet]
        public ActionResult panelOrdenes(string store_id)
        {
            Log.Debug("Panel para store_id " + store_id);
            int storeId;
            JUMPSELLER_STORES objJumpsellerStore = null;
            JumpsellerAPI objJumpsellerApi = null;
            db_shipexEntities context = new db_shipexEntities();
            if (Int32.TryParse(store_id, out storeId))
            {
                Log.Debug("Cargando datos para la store_id " + store_id);
                objJumpsellerStore = context.JUMPSELLER_STORES.Where(x => x.id_tienda_jumpseller == storeId && x.activo == true).FirstOrDefault();
                if (objJumpsellerStore != null)
                {
                    JUMPSELLER_CREDENCIALES_APP objCredenciales = context.JUMPSELLER_CREDENCIALES_APP.Where(x => x.store_id == objJumpsellerStore.id).FirstOrDefault();
                    Log.Debug("Tiene datos?" + (objCredenciales != null));
                    if (objCredenciales != null)
                    {
                        objJumpsellerApi = new JumpsellerAPI();
                        objJumpsellerApi.access_token = objCredenciales.access_token;
                        objJumpsellerApi.created_at = (int)objCredenciales.created_at;
                        objJumpsellerApi.refresh_token = objCredenciales.refresh_token;
                        objJumpsellerApi.token_type = objCredenciales.token_type;
                    }
                    else
                    {
                        //No encontro credenciales registradas, se envia al proceso de autorización
                        Log.Debug("Redirección a proceso de autorización. store_id: " + store_id + " no se encuentra registradas las credenciales");

CostosDeDespacho/CostosDeDespacho/Views/PanelJumpS/Index.cshtml
@model IEnumerable<CostosDeDespacho.Models.OrdenesJumpseller>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.order_id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.shipping_method_name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.customer_name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.customer_phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.customer_email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.customer_address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.customer_municipality)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.order_id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.status)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.shipping_method_name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.customer_name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.customer_phone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.customer_email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.customer_address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.customer_municipality)
        </td>
        <td>
            @Html.ActionLink("Confirmar", "Confirmar", new { id=item.order_id }) 
        </td>
    </tr>
}

</table>

CostosDeDespacho/CostosDeDespacho/Views/PanelJumpS/ProcesarOauth.cshtml
@{
    ViewBag.Title = "ProcesarOauth";
}

<h2>ProcesarOauth</h2>

CostosDeDespacho/CostosDeDespacho/Views/PanelJumpS/panelOrdenes.cshtml
@model IEnumerable<CostosDeDespacho.Models.PanelOrderJumpsellerViewModel>

<div class="row">
    <h1 class="">Ordenes Shipex</h1>
</div>
@using (Html.BeginForm("panelOrdenes", "PanelJumpS", FormMethod.Post))
{
    <div class="row">
        <div class="col-12 col-sm-6">
            <div class="row">
                <div class="col-6">
                    <div class="form-floating my-1">
                        <input type="date" class="form-control" id="" placeholder="" name="fecDesde">
                        <label for="">Fecha desde</label>
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-floating my-1">
                        <input type="date" class="form-control" id="" placeholder="" name="fecHasta">
                        <label for="">Fecha hasta</label>
                    </div>
                </div>
            </div>
        </div>
        <!--CLL: Hidden de id tienda-->
        <input type="hidden" value="@ViewBag.idJumpsellerStore" name="idJumpsellerStore" />
        <!--Fin dato-->
        <div class="col-12 col-sm-6">
            <div class="row">
                <div class="col-6">
                    <div class="form-floating my-1">
                        <input type="text" class="form-control" placeholder="" name="idOrden" id="idOrden" value="@(ViewBag.idOrden ?? "Num. orden")">
                        <label for="">N&uacute;mero de orden</label>

                    </div>
                </div>
                <div class="col-6">
                    <div class="form-floating my-1"> <button class="btn btn-primary my-3" type="submit">Buscar</button> </div>
                </div>
            </div>
        </div>
    </div>
}

<!-- tabla-->
<div class="grid">
    <div id="example_wrapper" class="dataTables_wrapper">
        <div class="dataTables_length" id="example_length">
            <table id="tblDatos" class="display responsive nowrap dtr-inline dataTable collapsed" role="grid" style="width:100%">
                <thead>
                    <tr>
                        <th class="checkbox" id="check_todos" width="60px"><input type="checkbox" class="select_orden_todos" name="seleccion_orden_todos" value="select_orden_todos"> <label>Selec. Todos</label></th>
                        <th data-priority="1">Pedido</th>
                        <th data-priority="2">Estado</th>
                        <th>Nombre cliente</th>
                        <th data-priority="3">Tel&eacute;fono</th>
                        <th>Email</th>
                        <th data-priority="4">Direcci&oacute;n env&iacute;o</th>
                        <th data-priority="5">Comuna</th>
                        <th>Estado Shipex</th>
                        <th data-priority="6">Tracking Shipex</th>
                        <th>Acci&oacute;n</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        @if (item.tracking == "-")
                        {
                            <td class="checkbox"><input type="checkbox" name="seleccion_orden" class="checkTable" value="select_orden" id="checkTodos" disabled></td>
                        }
                        else
                        {
                            <td class="checkbox"><input type="checkbox" name="seleccion_orden" class="checkTable" value="select_orden" id="checkTodos"></td>
                        }
                        <td>
                            @Html.DisplayFor(modelItem => item.id_orden_jumpseller)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.estadoOrdenJumpseller)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.nombreReceptor)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.telefono)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.email)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.direccionEnvio)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.comuna)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.estadoEnvioShipex)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.tracking)
                        </td>
                        <td>
                            @if (item.estadoEnvioShipex != "Confirmado")
                            {
                                @Html.ActionLink("Confirmar", "Confirmar", new { idTableOrden = item.id, id_store = @ViewBag.idJumpsellerStore })
                            }

                        </td>
                    </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="container-fluid text-center">
        <div class="col-12">
            <button type="submit" id="btnGenerarEtiqueta" class="btn btn-danger btn-block col-8">Generar Etiquetas</button>
        </div>
    </div>
</div>


@section Scripts {
    <script type="text/javascript">


        $(function () {
            $(document).on('click', '.select_orden_todos', function () {
                if ($(this).is(':checked')) {

                    $("#tblDatos tbody ").each(function () {
                        let tracking = $(this).find("td").eq(9).html().trim();
                        console.log(tracking)
                        if (tracking == "") {
                            $('.checkTable').prop("checked", false);
                        } else {
                            $('.checkTable').prop("checked", true);
                        }
                    });
                }
                else {
                    $('.checkTable').prop("checked", false);
                }
            });

            $('#tblDatos').DataTable({
                dom: 'lBfrtip',
                responsive: true,
                "page": 10,
                "language": {
                    "info": "Página _PAGE_ de _PAGES_, total de registros _MAX_",
                    "zeroRecords": "No hay información",
                    "search": "Buscar :",
                    "lengthMenu": "Mostrar _MENU_ por página",
                    "infoFiltered": "(Filtro de _MAX_ registros)",
                    "paginate": {
                        "previous": "Anterior",
                        "next": "Siguiente"
                    }
                },
            });

        });

        $("#btnGenerarEtiqueta").click(function (e) {
            e.preventDefault();


            let fileName = "EtiquetaJS";
            let seleccion = [];

            $("#tblDatos tr td input[type='checkbox']:checked").each(function () {

                row = $(this).closest('tr');

                if (row.find('td:eq(9)').text().trim() != "-") {
                    seleccion.push({
                        codigo_despacho_shipex: row.find('td:eq(9)').text().trim()
                    });
                }
            });

            console.log(seleccion)

            if (seleccion.length === 0) {
                alert("Debe seleccionar al menos 1 registro que se muestra en la tabla");
                //swal("Advertencia", "Debe seleccionar al menos 1 registro que se muestra en la tabla", 'warning');
                return
            } else {
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("GenerarPDF_Masivo")',
                    data: '{_trackingJS:' + JSON.stringify(seleccion) + '}',
                    dataType: 'json',
                    contentType: 'application/json;charset=utf-8',

                    success: function (resultData) {

                        if (resultData.success) {
                            window.location = "/costos_despacho/PanelJumpS/DownloadInvoice" + "?fName=" + resultData.fName;
                        }
                    }
                });
            }
        });

    </script>
}

CostosDeDespacho/CostosDeDespacho/Views/PanelJumpS/setTokenShipex.cshtml
@{

    ViewBag.Title = "Configuración App";
}

@model CostosDeDespacho.Models.JUMPSELLER_STORES


@*<h2>Configuraci&oacute;n App</h2>*@
    <div class="col-12 col-sm-5 mx-auto">
        <p>Ingreso de token de configuraci&oacute;n para el funcionamiento de la app. En caso de no tener el token cont&aacute;ctanos al correo <a href="mailto:ventas@shipex.cl">ventas@shipex.cl</a></p>
        @using (Html.BeginForm("setTokenShipex", "PanelJumpS", FormMethod.Post))
        {
            <h4 class="text-start">Ingrese token </h4>
            <input type="hidden" value="@ViewBag.idJumpsellerStore" name="idJumpsellerStore" />
            <input class="form-control form-control-lg" type="text" placeholder="" aria-label=".form-control-lg example" id="token" name="token" value="@(ViewBag.api_token ?? String.Empty)">
            <button class="btn btn-primary my-4" type="submit">Registrar</button>
        }
    </div>